### ISSUE TITLE
`vagrant up` no longer working - corrupt `Gemfile.lock`

### ISSUE THREAD

**Issue by nathenharvey** [jedi4ever/devopsdays-webby#2316]
When checking out the master branch, I am getting an error on `vagrant up` that is preventing me from testing changes locally.

```
==> default: Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES
==> default: section: 'bones'
```

**Comment by pmoosh** [comment]
Weird - this one popped up again today... Had to add the bundler version in the Dockerfile.
