### ISSUE TITLE
devopsdays Paris 2015 "site" looks like it's been reset

### ISSUE THREAD

**Issue by jooooooon** [jedi4ever/devopsdays-webby#2784]
Hi,

I needed to look something up about our last event, and headed to http://www.devopsdays.org/events/2015-paris/. There's nothing there anymore except the default content. We had a bunch of things (sponsors and a program, for example).

However, checking the commits, nothing has changed in the 2015-paris directory. Is there a chance another recent commit broke this? If so, maybe other events are broken too?

I'd love to debug it, but it's way past my bedtime and my Ruby-foo is really not great. This is the best I can do right now :)

Jon

**Comment by jedi4ever** [comment]
@jooooooon the system has moved to a https://github.com/devopsdays/devopsdays-web

**Comment by jooooooon** [comment]
Ah. Thanks Patrick!
