### ISSUE TITLE
'2016 Bangalore' event content on web but not here

### ISSUE THREAD

**Issue by abhishekkr** [jedi4ever/devopsdays-webby#2785]
I can visit `http://www.devopsdays.org/events/2016-bangalore/welcome/` for 2016 Bangalore event but can't find data for it in this repo.
Are the portal and this codebase not in sync.
I needed to update the event pages.

**Comment by bridgetkromhout** [comment]
We moved to https://github.com/devopsdays/devopsdays-web/. Thanks.
